import { Linking, Alert } from 'react-native';

export interface SendOptions {
  email?: string;
  phone?: string;
  subject?: string;
  body?: string;
  attachmentPath?: string;
}

export class SendService {
  /**
   * Send document via email
   * Note: Attachment support is limited on mobile. This opens the default email client.
   * TODO: Implement backend service for full email sending with attachments
   */
  static async sendEmail(options: SendOptions): Promise<void> {
    const { email, subject, body, attachmentPath } = options;
    
    if (!email) {
      throw new Error('Email address is required');
    }
    
    try {
      let mailtoUrl = `mailto:${email}`;
      const params = [];
      
      if (subject) {
        params.push(`subject=${encodeURIComponent(subject)}`);
      }
      
      if (body) {
        params.push(`body=${encodeURIComponent(body)}`);
      }
      
      if (params.length > 0) {
        mailtoUrl += `?${params.join('&')}`;
      }
      
      const canOpen = await Linking.canOpenURL(mailtoUrl);
      if (canOpen) {
        await Linking.openURL(mailtoUrl);
        
        if (attachmentPath) {
          Alert.alert(
            'Attachment Note',
            'Please manually attach the PDF file from your device storage:\n\n' + attachmentPath,
            [{ text: 'OK' }]
          );
        }
      } else {
        throw new Error('No email app available');
      }
    } catch (error) {
      console.error('Error sending email:', error);
      throw new Error('Failed to open email app');
    }
  }
  
  /**
   * Send document via SMS
   * Opens the default SMS app with the message
   */
  static async sendSMS(options: SendOptions): Promise<void> {
    const { phone, body } = options;
    
    if (!phone) {
      throw new Error('Phone number is required');
    }
    
    try {
      // Clean phone number (remove formatting)
      const cleanPhone = phone.replace(/[^\d]/g, '');
      
      let smsUrl = `sms:${cleanPhone}`;
      
      if (body) {
        smsUrl += `?body=${encodeURIComponent(body)}`;
      }
      
      const canOpen = await Linking.canOpenURL(smsUrl);
      if (canOpen) {
        await Linking.openURL(smsUrl);
      } else {
        throw new Error('No SMS app available');
      }
    } catch (error) {
      console.error('Error sending SMS:', error);
      throw new Error('Failed to open SMS app');
    }
  }
  
  /**
   * Generate default email subject for document
   */
  static generateEmailSubject(docType: 'quote' | 'invoice', docNumber: string, businessName: string): string {
    const type = docType.charAt(0).toUpperCase() + docType.slice(1);
    return `${type} ${docNumber} from ${businessName}`;
  }
  
  /**
   * Generate default email body for document
   */
  static generateEmailBody(
    docType: 'quote' | 'invoice',
    docNumber: string,
    customerName: string,
    businessName: string,
    total?: number
  ): string {
    const type = docType.charAt(0).toUpperCase() + docType.slice(1);
    const totalText = total ? ` for ${new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(total)}` : '';
    
    return `Hi ${customerName},

Please find your ${type.toLowerCase()} ${docNumber}${totalText} attached.

${docType === 'quote' 
  ? 'Please review the quote and let us know if you have any questions. We look forward to working with you!'
  : 'Payment is due according to the terms specified in the invoice. Thank you for your business!'
}

Best regards,
${businessName}

--
This ${type.toLowerCase()} was generated by MakeItPlumb`;
  }
  
  /**
   * Generate default SMS body for document
   */
  static generateSMSBody(
    docType: 'quote' | 'invoice',
    docNumber: string,
    businessName: string,
    total?: number
  ): string {
    const type = docType.charAt(0).toUpperCase() + docType.slice(1);
    const totalText = total ? ` for ${new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(total)}` : '';
    
    return `${type} ${docNumber}${totalText} from ${businessName}. Please check your email for the PDF attachment.`;
  }
}

// TODO: Backend integration for full-featured sending
/*
Future backend implementation should include:

1. Email Service Integration (SendGrid, AWS SES, etc.)
   - Proper attachment handling
   - Email templates
   - Delivery tracking
   - Bounce handling

2. SMS Service Integration (Twilio, AWS SNS, etc.)
   - Link to PDF in cloud storage
   - Delivery tracking
   - Opt-out handling

3. Cloud Storage Integration
   - Upload PDFs to secure cloud storage
   - Generate time-limited access links
   - Automatic cleanup of old files

Example backend endpoints:
- POST /api/send/email
- POST /api/send/sms
- GET /api/documents/:id/download

This would enable:
- Reliable delivery
- Professional templates
- Tracking and analytics
- Better attachment handling
*/
